name: ekklesia
description: "A Church Engagement App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/church_welcome.jpg
    - assets/images/a_place_for_everyone.jpeg
    - 'assets/images/grow_your_faith.jpeg'

  fonts:
    - family: Inter
      fonts:
      - asset: assets/fonts/Inter-Regular.ttf
      - asset: assets/fonts/Inter-Italic.ttf
        style: italic
